- id: sort-xml
  name: Sort XML attributes using XSLT
  entry: scripts/sort-xml.sh
  language: script
  files: \.xml$
- id: xmlstarlet-format
  name: Format XML using xmlstarlet
  entry: scripts/xmlstarlet-format.sh
  language: script
  files: \.xml$
- id: attribute-in-line
  name: Put each attribute in its own line
  entry: scripts/each-attribute-in-line.sh
  language: script
  files: \.xml$